AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - features/**/*
    - db/**/*
    - spec/factories/**/*
LineLength:
  Max: 120
  Enabled: true
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
